services:
  - type: web
    name: whatsapp-monitor
    env: node
    plan: free
    buildCommand: npm ci --omit=dev --ignore-scripts
    startCommand: node whatsapp-optimized.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: HEADLESS
        value: true
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium-browser
    healthCheckPath: /health
    autoDeploy: false